---
title: "Differentiate for higher profits &#8211; create a monopoly and raise your prices"
path: "/differentiate-for-higher-profits-create-a-monopoly-and-raise-your-prices/"
source: "rest"
seo:
  title: "Differentiate for higher profits - create a monopoly and raise your prices - Ruckus Creative"
  description: "\"What makes you so special and why should I buy from you and not your competitor down the street?\" – How to create compelling and motivational brand strategies, ad campaigns, brochures, and other marketing communications"
  canonical: "https://ruckuscreative.com/differentiate-for-higher-profits-create-a-monopoly-and-raise-your-prices/"
  ogImage: null
pubDate: "2012-08-22T06:18:33"
updatedDate: "2012-08-22T21:21:06"
---
<p>Most companies sell the same thing as their competitor. Usually there is not that much difference in what you offer, as compared to your competition. But you can’t sell “the same thing” as some other company and be profitable. You need to communicate why you are different, unique, valuable, and why the market should buy from you and no one else.</p>
<p>When 2 companies overtly advertise the same thing, the only way to be competitive is to lower prices, undercut the competition and lower profits – not the healthiest way to run a business.<br>
Look at Tylenol® – they sell “premium non-aspirin pain relief,” that’s their brand. Then Savons® comes along and says “we sell the same thing as Tylenol” and can only compete by undercutting prices dramatically. Tylenol commands 37% more at the cash register and Savons still can’t compete with Tylenol in sales! And at 37% lower in price, this is Savons normal pricing – they typically have to discount their products heavily to move them (ie: buy one – get one free, $2 off a $5 bottle, etc.) and they still are out-sold by Tylenol. The reason is, Savons is marketing their “me-too” positioning. If a company advertises a “me-too” product, than it automatically perceived as a cheap knock-off, and nowhere near the same premium “quality” as the original, even if it’s the same exact ingredients. Even Savon’s packaging design screams “me-too,” it copied Tylenol’s so closely Savons was court-ordered to redesign it.</p>
<p>“Me-too” positioning and advertising means you have no other choice than to lower your price to compete. What you want to do is create the perception that only you offer whatever product or service you offer, and in essence, create a monopoly where you can raise your price and raise your margins. If the market can only buy “X” product or service from you, you can essentially charge whatever you want. Create differentiation, create value and create profits.<br>
Differentiation is not a new concept, look at the pros: Apple® is running a great ad campaign right now. It’s 4 pages, and the first page has just one question: “What’s the difference between a Mac and a PC?” The second page answers, ” Where do we begin?” And then lists all the ways they are different.</p>
<p><strong>Fight fire with fire? Nope. Fight fire with water.<br>
Here are a few ways to help create differentiation:</strong></p>
<p><strong>1) Be first.</strong>&nbsp;The first company in a new industry, category or segment owns 100% of that niche. Once competitors knock-off your product/service, they’ll be fighting for leftovers. Usually, the leader owns the lions share of the market and is not easily removed.</p>
<p><strong>2) If you’re not first, try to add something unique to your product/service, or position it to create a new segment.</strong>&nbsp;The aspirin market was entrenched when Bufferin® added a buffering agent to create a new segment – buffered aspirin, which they immediately owned 100% of, and still dominate years later.</p>
<p><strong>3) Look deep within.</strong>&nbsp;Even if it seems as your company sells about the same thing as everybody else, there is always a kernel of an idea there somewhere that you can build a differentiated and valuable brand on. Maybe it’s why the company started in the first place, what was the original “big idea” that your company was based on? Or maybe it’s where you’ve evolved to, or are going to be in the near future. And when looking for that idea to build your brand on, don’t just list the first 10 or 12 ideas – your competitors will be listing those same 12 ideas: “customer service, quality, price, our people make us different… etc.,” you want to list 100, then 200, then 300. That’s when you’ll uncover truly unique ideas of why people should buy from you and not the competition.</p>
<p><strong>4) Differentiation is based on perception, not always reality.</strong> A Rolex® and a Timex® tell the same time. If you have to adjust the Timex once a year, but not the Rolex, is that worth an extra few thousand dollars? Timex knows their watches are perceived as just accessories, and they make them as light as possible so people don’t mind wearing them. On the other hand, Rolex adds weight to theirs to make it heavier, and create the perception it’s more valuable – “man, there must be a lot of gold in here, feel how heavy it is!” Rolex even tells you their watches are valuable through their pricing – “they must be good at that price.” Again, realistically, there’s not that much difference between a Rolex and a Timex, they both tell about the same time.</p>
<p>Here is another reality check. Porsche® is regarded as higher “quality” than Toyota®. But which do you think breaks down less? Just like Tylenol and Savons, the competitor that creates the perception of higher value, gets the higher profits.</p>
<p>When building a differentiation, pay attention to both the macro and micro views. First, look at the big picture, the overall brand strategy and positioning. Then, look at everything, down to all the details – from the color of your logo to the color you paint your product. For example, look at Coke®, Pepsi® and Mountain Dew®: they all sell the same thing, sugary bubble water in a 12 oz. can. But they can’t have you believe they sell the same thing as their competitor so they start by coloring their cans differently. Coke is first and paints their can red, based mostly on the color of their soda. Then Pepsi comes along and paints their can the opposite color – blue. Then Mountain Dew comes along and they take to opposite color – green. Their brand’s core values are different too: Coke is “Refreshment,” Pepsi is “Change,” and Mountain Dew is “Attitude.” They even go after opposite markets – Coke takes the adult market, Pepsi takes Generation X, and Mountain Dew takes Generation Y-not.</p>
<p>Look at logos for another example. Say you came to an agency like ours and asked us to design you a logo that separates you from the competition and differentiates you from all others. After doing our homework and creating some design comps, we finally say we are ready to unveil your new logo to you and we tell you “to differentiate your company, we’ve decided your new logo should be orange and purple.” At this point most Company Executives would tell us that their president likes blue and it needs to be a blue logo, and throw us out on our ear. But FedEx didn’t. And they have one of the most recognizable logos in the world.</p>
<p>Or look at the financial industry – it seems everybody uses the exact same color, it’s a sea of blue logos, or maybe some companies will sport a wild and crazy blue and gray logo. Then, a new, fresh powerhouse comes along – ING®, and they take the opposite color, orange. And it’s even the opposite shape – a circle compared to the typical of rectangle or square. They even have an internal cheerleading cry of “how orange are you?” And ING takes the country by storm, with a large advertising budget to be sure, but starting with the most basic of basics, a logo that differentiates them from the rest and gives the market a reason to think they are different.<br>
From a creative standpoint, and marketing standpoint, differentiation is a key to success. Look at all aspects of your product, service, offer and brand to see how you can separate yourself. From your positioning, to selecting the color of your logo, to the market you choose to target, start by doing the opposite of what your competitors are doing, and carry that concept through market, message, market, positioning, strategy and so on. Unless your brand is “we offer the cheapest products in town,” you should create the perception you have a monopoly, raise your rates, raise your profits and create value by differentiating your company.</p>
<p><strong>Kevin Daniels</strong> is a Principle rabble-rouser at Ruckus Creative, llc, with 20 years in advertising and marketing.<br>
<strong>Ruckus Creative</strong> is a results-driven, full-service creative and branding agency<br>
<em>“Business results through strategic creative.”</em><br>
714-514-1482<br>
4 Hearthside Rd.<br>
Ladera Ranch, CA 92694<br>
<a href="/">www.ruckuscreative.com</a></p>
